import type { WechatTheme } from './index'

export const freshGreenTheme: WechatTheme = {
  name: '清新绿',
  id: 'fresh-green',
  macCodeBlock: true,
  codeTheme: 'atom-one-dark',
  flagHeading: true,
  styles: {
    base: 'font-family: -apple-system, BlinkMacSystemFont, "Helvetica Neue", "PingFang SC", "Microsoft YaHei", sans-serif; font-size: 15px; color: #333; line-height: 1.8; word-break: break-word;',
    h1: 'font-size: 22px; font-weight: 700; color: #333; margin: 1.2em 0 0.6em; padding: 0;',
    h2: 'font-size: 18px; font-weight: 700; color: #06c160; margin: 1em 0 0.5em; padding: 0; --h2-bg: #06c160; border-radius: 0;',
    h3: 'font-size: 16px; font-weight: 600; color: #1B8C3E; margin: 0.8em 0 0.4em; padding-left: 10px; border-left: 3px solid #06c160;',
    h4: 'font-size: 15px; font-weight: 600; color: #06c160; margin: 0.6em 0 0.3em;',
    h5: 'font-size: 14px; font-weight: 600; color: #4FBF7F; margin: 0.5em 0 0.3em;',
    h6: 'font-size: 13px; font-weight: 600; color: #6bc98b; margin: 0.5em 0 0.3em;',
    p: 'margin: 0.8em 0; line-height: 1.8; color: #3d3d3d;',
    strong: 'font-weight: 700; color: #2c3e50;',
    em: 'font-style: italic; color: #666;',
    del: 'text-decoration: line-through; color: #aaa;',
    a: 'color: #06c160; text-decoration: none; border-bottom: 1px solid #a8e6cf;',
    blockquote: 'margin: 1em 0; padding: 14px 20px; border-left: 4px solid #06c160; background: #f0fdf4; color: #555; border-radius: 0 8px 8px 0; font-size: 15px; line-height: 1.8;',
    code: 'background: #f0fdf4; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; color: #1B8C3E; font-family: "SF Mono", Menlo, Consolas, monospace;',
    pre: 'background: #282c34; padding: 0 0 16px; border-radius: 10px; overflow-x: auto; font-size: 14px; line-height: 1.6; margin: 1em 0; font-family: "SF Mono", Menlo, Consolas, monospace; color: #abb2bf;',
    ul: 'margin: 0.8em 0; padding-left: 2em;',
    ol: 'margin: 0.8em 0; padding-left: 2em;',
    li: 'margin: 0.3em 0; line-height: 1.8;',
    img: 'max-width: 100%; border-radius: 6px; margin: 0.8em 0;',
    table: 'width: 100%; border-collapse: collapse; margin: 1em 0; font-size: 14px;',
    th: 'border: 1px solid #dcfce7; padding: 10px 14px; background: #f0fdf4; font-weight: 600; text-align: left; color: #1B8C3E;',
    td: 'border: 1px solid #dcfce7; padding: 10px 14px; text-align: left;',
    hr: 'border: none; height: 1px; background: linear-gradient(to right, transparent, #06c160, transparent); margin: 1.5em 0;',
  },
}
